version: '3.8'

services:
  postgres_dev:
    image: postgres:14
    container_name: encafeinados_db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffee_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: